---
configs:
    use: 'small'
    small:
        memory: 2048
        cores: 2
    medium:
        memory: 4096
        cores: 2
    large:
        memory: 8192
        cores: 4
    proxied:
        memory: 4096
        cores: 2
        # Proxy URL that will be configured in various places
        proxy_url: http://proxy:8123
        # Domains excluded from the proxy, comma separated list
        proxy_excludes: .internal.net,.dmz.net
        # Force search domain in /etc/resolv.conf
        search_domain: company.com
    # settings in 'default' are applied to all configurations
    default:
        # Limit DNS resolution to IPV4
        ipv4only: true
