version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: pdouble16/packer-build-base:202005.1
        user: root

    steps:
      - checkout

      - setup_remote_docker

      # This cache is for the docker images. Layer caching is early, we use a tarball created by
      # `docker save` to cache our images.
      - restore_cache:
          keys:
            - v5-dockerimage-{{ checksum "packer.json" }}}
            - v5-dockerimage-

      - restore_cache:
          keys:
            - v4-vagrant-{{ checksum "environments/dev/hieradata/common.yaml" }}}
            - v4-vagrant-

      - run:
          name: Restore Docker Public Image Cache
          command: |
            set -x
            if [[ -s /home/linux-dev-workstation/cache/docker/image.tar.gz ]]; then
              zcat /home/linux-dev-workstation/cache/docker/image.tar.gz | docker load
            fi

      - run:
          name: Restore vagrant-cache
          no_output_timeout: 30m
          command: |
            docker create --name vagrant-cache -v /home/linux-dev-workstation/.vagrant/machines/default/cache:/cache alpine:latest
            if [[ -d /home/linux-dev-workstation/.vagrant/machines/default/cache ]]; then
              # Keep the cache from growing without bound
              find /home/linux-dev-workstation/.vagrant/machines/default/cache -type f -mtime +60 -delete -print
              docker cp /home/linux-dev-workstation/.vagrant/machines/default/cache/. vagrant-cache:/cache
            fi

      - run:
          name: docker.io login
          command: |
            set -e
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" docker.io

      - run:
          name: Packer Build
          no_output_timeout: 1h
          command: |
            if [[ -z "${CIRCLE_TAG}" ]]; then
              cat packer.json | jq 'del(."post-processors" | .[] | .[] | select(.type == "vagrant-cloud"))' > packer-circleci.json
            else
              cp packer.json packer-circleci.json
            fi

            /usr/bin/packer build -color=false -only=docker -var version=${CIRCLE_TAG:-latest} ${CIRCLE_TAG:+-var no_release=false} packer-circleci.json

      - run:
          name: Retrieve vagrant-cache
          no_output_timeout: 30m
          command: |
            mkdir -p /home/linux-dev-workstation/.vagrant/machines/default/cache
            docker cp vagrant-cache:/cache/. /home/linux-dev-workstation/.vagrant/machines/default/cache
            docker rm vagrant-cache

      - run:
          name: Build Docker Public Image Cache
          no_output_timeout: 30m
          command: |
            set -x
            mkdir -p /home/linux-dev-workstation/cache/docker
            docker images --format '{{.Repository}}:{{.Tag}}' | grep -v "linux-dev-workstation\|:<none>" | xargs -r docker save | gzip -9 > /home/linux-dev-workstation/cache/docker/image.tar.gz

      - save_cache:
          key: v5-dockerimage-{{ checksum "packer.json" }}
          paths:
            - /home/linux-dev-workstation/cache/docker

      - save_cache:
          key: v4-vagrant-{{ checksum "environments/dev/hieradata/common.yaml" }}}
          paths:
            - /home/linux-dev-workstation/.vagrant/machines/default/cache

workflows:
  version: 2
  untagged-build:
    jobs:
      - build:
          filters:
            branches:
              only: /^master/
            tags:
              ignore: /.*/
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9][0-9][0-9][0-9][0-9][0-9][.].*/
            branches:
              ignore: /.*/
