version: 2
jobs:
  build:
    working_directory: /home/linux-dev-workstation
    docker:
      - image: pdouble16/packer-build-base:201806.1
        user: root

    steps:
      - checkout

      - setup_remote_docker

      # This cache is for the docker images. Layer caching is early, we use a tarball created by
      # `docker save` to cache our images.
      - restore_cache:
          keys:
            - v5-dockerimage-{{ .Branch }}-{{ checksum "centos.json" }}}
            - v5-dockerimage-{{ .Branch }}-
            - v5-dockerimage-

      - restore_cache:
          keys:
            - v4-vagrant-{{ .Branch }}-{{ .Revision }}
            - v4-vagrant-{{ .Branch }}-
            - v4-vagrant-

      - run:
          name: Restore Docker Public Image Cache
          command: |
            set -x
            if [[ -s /home/linux-dev-workstation/cache/docker/image.tar.gz ]]; then
              zcat /home/linux-dev-workstation/cache/docker/image.tar.gz | docker load
            fi

      - run:
          name: docker.io login
          command: |
            set -e
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" docker.io

      - run:
          name: Docker Image Build
          no_output_timeout: 1h
          command: |
            /usr/bin/packer build -color=false -only=docker -var version=${CIRCLE_TAG:-latest} centos.json

      - run:
          name: Build Docker Public Image Cache
          no_output_timeout: 30m
          command: |
            set -x
            mkdir -p /home/linux-dev-workstation/cache/docker
            docker images --format '{{.Repository}}:{{.Tag}}' | grep -v "linux-dev-workstation\|:<none>" | xargs -r docker save | gzip -9 > /home/linux-dev-workstation/cache/docker/image.tar.gz

      - save_cache:
          key: v5-dockerimage-{{ .Branch }}-{{ checksum "centos.json" }}
          paths:
            - /home/linux-dev-workstation/cache/docker

      - save_cache:
          key: v4-vagrant-{{ .Branch }}-{{ .Revision }}
          paths:
            - /home/linux-dev-workstation/.vagrant/machines/default/cache
