version: '3.3'

volumes:
  aptcache:

services:
  aptcache:
    image: pdouble16/docker-apt-cacher-ng:3.3.1-1
    restart: always
    ports:
      - "3142:3142"
    volumes:
      - aptcache:/var/cache/apt-cacher-ng
