# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.provision "builder", type: "shell",
    inline: JSON.parse(File.read('builder.json'))["provisioners"].collect { |e| e['inline'] }.flatten.join("\n")
end
